
no_index: 
  directory: 
    - inc
    - t
generated_by: Module::Install version 0.62
distribution_type: module
version: 0.01
name: CPAN-Cache
author: Adam Kennedy <cpan@ali.as>
license: perl
build_requires: 
  Test::More: 0.47
  File::Spec: 0.80
requires: 
  URI::ToDisk: 1.09
  IO::File: 0
  File::HomeDir: 0.54
  File::Spec: 0.80
  Carp: 0
  perl: 5.005
  Params::Util: 0.10
  File::Path: 0
  LWP::Simple: 0
abstract: Locally-stored logical subset of a CPAN mirror
